# RA, 2020-12-21

from twig import log
from datetime import datetime, timezone
from contextlib import redirect_stdout
from pathlib import Path

from tcga.utils import relpath, First

now = datetime.now(tz=timezone.utc).strftime("%Z-%Y%m%d-%H%M%S")

f = First((Path(__file__).parent / "b_cellwise").glob).each(relpath).each(Path).then(list)

with redirect_stdout((Path(__file__).parent / "readme.md").open('w')):
    print("This file was generated by", Path(__file__).name, F"({now})")
    print()

    for (hist, tsne) in zip(f("hist/*.png"), f("tsne/*.png")):
        log.info(F"{hist.stem}")

        assert (hist.stem == tsne.stem)

        print(hist.stem)
        print()
        print(F"![{hist.stem}]({hist})")
        print(F"![{tsne.stem}]({tsne})")
        print()
